server:
  options:
    debug:
      request:
        - error
        - request-internal
    connections:
      state:
        ignoreErrors: true
        clearInvalid: true

  connection:
    port: 3000

public:
  enable: true
  options:
    path: public
    redirectToSlash: true
    index: false,
    lookupCompressed: true

session:
  enable: true
  options:
    cookie:
      name: sid
      password: 24CC51A1D75D4736AEB38782617DEDC02E7A79ECD6FA9D49545386B138AC6658
      ttl: 86400000
      domain: null
      path: /
      encoding: none
      clearInvalid: false
      isSecure: false
      isHttpOnly: false
    auth:
      roles:
        - SUPER
        - MANAGER
        - CLIENT
        - USER
      jwt:
        secret: 24CC51A1D75D4736AEB38782617DEDC02E7A79ECD6FA9D49545386B138AC6658
        algorithms: HS256
      cookie:
        secret: 24CC51A1D75D4736AEB38782617DEDC02E7A79ECD6FA9D49545386B138AC6658
        algorithms: HS256

backend:
  enable: true
  prefix: /api
  options:
    enableTesting: true

frontend:
  enable: true
  options: {}
  helmet:
    title: 'Hapi React Isomorphic Boilerplate'
    description: '基于 HapiJS, ReactJS 的前后端同构样板'
    head:
      titleTemplate: '%s | HRIB'
      meta:
        -
          charset: utf-8
        -
          http-equiv: X-UA-Compatible
          content: IE=edge
        -
          name: viewport
          content: 'width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1'
      link:
        - rel: stylesheet
          href: /static/css/demo.css
        - rel: 'favicon icon'
          href: /static/img/favicon.png

proxy:
  enable: true
  prefix: /proxy
  options:
    proxies:
      -
        enable: true
        name: testing
        uri: http://127.0.0.1:3000
        passThrough: true
        xforward: true
        methods:
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          - OPTIONS

swagger:
  enable: true
  options:
    info:
      title: 'Hapi React Isomorphic Boilerplate'
      description: '本文由 Hapi Swagger 插件自动生成'
    documentationPath: '/developers/documentation'
    pathPrefixSize: 3
    basePath: /api
    securityDefinitions:
      jwt:
        type: apiKey
        name: Authorization
        in: header
      security:
        -
          jwt:

logger:
  ops:
    interval: 60000
  reporters:
    consoleReporter:
      - module: good-squeeze
        name: Squeeze
        args:
          - ops: '*'
            error: '*'
            log: '*'
            request: '*'
            response: '*'
            server: '*'
      - module: good-console
      - stdout
