server:
  connection:
    host: 127.0.0.1
    port: 3000
    uri: http://127.0.0.1:3000
proxy:
  enable: true
  prefix: /proxy
  options:
    proxies:
      -
        enable: true
        name: testing
        uri: http://127.0.0.1:3000
        passThrough: true
        xforward: true
        methods:
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          - OPTIONS
        headers:
          - x-auth-ua
          - x-auth-token
          - x-auth-openid
          - x-auth-is-ios
          - x-auth-is-app
          - x-auth-is-android
          - x-auth-is-wechat
          - x-auth-uuid
          - x-auth-uaid
