server:
  connection:
    port: 4000
proxy:
  enable: true
  prefix: /proxy
  options:
    proxies:
      -
        enable: true
        name: testing
        uri: http://127.0.0.1:4000
        passThrough: true
        xforward: true
        methods:
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          - OPTIONS
        headers:
          - x-auth-ua
          - x-auth-token
          - x-auth-openid
          - x-auth-is-ios
          - x-auth-is-app
          - x-auth-is-android
          - x-auth-is-wechat
          - x-auth-uuid
          - x-auth-uaid

logger:
  ops:
    interval: 100000
  reporters:
    fileReporter:
      - module: good-squeeze
        name: Squeeze
        args:
          - ops: '*'
            error: '*'
            log: '*'
            request: '*'
            response: '*'
      - module: good-squeeze
        name: SafeJson
      - module: good-file
        args:
          - 'logs/hrib.log'
